# Try to find the taco library
#  TACO_FOUND - system has taco lib
#  TACO_INCLUDE_DIRS - the include directories needed
#  TACO_LIBRARIES - libraries needed

FIND_PATH(TACO_INCLUDE_DIR NAMES taco.h)

FIND_LIBRARY(TACO_LIBRARY NAMES libtaco)

SET(taco_LIBRARIES ${TACO_LIBRARY})
SET(taco_INCLUDE_DIRS ${TACO_INCLUDE_DIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TACO DEFAULT_MSG TACO_LIBRARY TACO_INCLUDE_DIR)

MARK_AS_ADVANCED(TACO_INCLUDE_DIR TACO_LIBRARY)
